// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Client")>]
[<assembly: AssemblyProductAttribute("GASS")>]
[<assembly: AssemblyDescriptionAttribute("GEHA Alert Suppression System")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Client.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Client"
    let [<Literal>] AssemblyProduct = "GASS"
    let [<Literal>] AssemblyDescription = "GEHA Alert Suppression System"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Client.Tests"
