// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.SignalR")>]
[<assembly: AssemblyProductAttribute("Fable.SignalR")>]
[<assembly: AssemblyDescriptionAttribute("Fable and server bindings for SignalR.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Fable.SignalR.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.SignalR"
    let [<Literal>] AssemblyProduct = "Fable.SignalR"
    let [<Literal>] AssemblyDescription = "Fable and server bindings for SignalR."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Fable.SignalR.Tests"
